### ISSUE TITLE
 Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

### ISSUE THREAD

**Issue by 13567436138** [Yolean/kubernetes-mysql-cluster#16]
Events:
  Type     Reason                 Age              From               Message
  ----     ------                 ----             ----               -------
  Normal   Scheduled              8m               default-scheduler  Successfully assigned mariadb-1 to node3
  Normal   SuccessfulMountVolume  8m               kubelet, node3     MountVolume.SetUp succeeded for volume "conf"
  Normal   SuccessfulMountVolume  8m               kubelet, node3     MountVolume.SetUp succeeded for volume "initdb"
  Normal   SuccessfulMountVolume  8m               kubelet, node3     MountVolume.SetUp succeeded for volume "default-token-m5z8x"
  Normal   SuccessfulMountVolume  8m (x2 over 8m)  kubelet, node3     MountVolume.SetUp succeeded for volume "pvc-6a2124d5-3ae5-11e8-8dec-001e9098365d"
  Normal   Pulling                8m               kubelet, node3     pulling image "mariadb:10.2.12@sha256:862de06a9b35f001e87bbefbb49008e84a59c4afd089c9a320947a9ae0e7cf1a"
  Normal   Pulled                 3m               kubelet, node3     Successfully pulled image "mariadb:10.2.12@sha256:862de06a9b35f001e87bbefbb49008e84a59c4afd089c9a320947a9ae0e7cf1a"
  Normal   Created                3m               kubelet, node3     Created container
  Normal   Started                3m               kubelet, node3     Started container
  Normal   Pulling                3m               kubelet, node3     pulling image "prom/mysqld-exporter@sha256:a1eda24a95f09a817f2cf39a7fa3d506df88e76ebdc08c0293744ebaa546e3ab"
  Normal   Pulled                 3m               kubelet, node3     Successfully pulled image "prom/mysqld-exporter@sha256:a1eda24a95f09a817f2cf39a7fa3d506df88e76ebdc08c0293744ebaa546e3ab"
  Normal   Started                3m               kubelet, node3     Started container
  Normal   Created                3m               kubelet, node3     Created container
  Normal   Pulled                 2m (x2 over 3m)  kubelet, node3     Container image "mariadb:10.2.12@sha256:862de06a9b35f001e87bbefbb49008e84a59c4afd089c9a320947a9ae0e7cf1a" already present on machine
  Normal   Started                2m (x2 over 3m)  kubelet, node3     Started container
  Normal   Created                2m (x2 over 3m)  kubelet, node3     Created container
  Warning  Unhealthy              1m (x6 over 3m)  kubelet, node3     Readiness probe failed: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by solsson** [comment]
The readiness probe fails, and probably for a reason. Check the logs for that pod.
