### ISSUE TITLE
system error: 104 /bin/sh: 1: [: =: argument expected

### ISSUE THREAD

**Issue by 13567436138** [Yolean/kubernetes-mysql-cluster#17]
Events:
  Type     Reason                 Age              From               Message
  ----     ------                 ----             ----               -------
  Normal   Scheduled              2m               default-scheduler  Successfully assigned mariadb-1 to node5
  Normal   SuccessfulMountVolume  2m               kubelet, node5     MountVolume.SetUp succeeded for volume "initdb"
  Normal   SuccessfulMountVolume  2m               kubelet, node5     MountVolume.SetUp succeeded for volume "conf"
  Normal   SuccessfulMountVolume  2m               kubelet, node5     MountVolume.SetUp succeeded for volume "default-token-m5z8x"
  Normal   SuccessfulMountVolume  2m (x2 over 2m)  kubelet, node5     MountVolume.SetUp succeeded for volume "pvc-47bb437f-3aec-11e8-8dec-001e9098365d"
  Normal   Pulled                 2m               kubelet, node5     Container image "mariadb:10.2.12@sha256:862de06a9b35f001e87bbefbb49008e84a59c4afd089c9a320947a9ae0e7cf1a" already present on machine
  Normal   Created                2m               kubelet, node5     Created container
  Normal   Started                2m               kubelet, node5     Started container
  Normal   Pulled                 2m               kubelet, node5     Container image "mariadb:10.2.12@sha256:862de06a9b35f001e87bbefbb49008e84a59c4afd089c9a320947a9ae0e7cf1a" already present on machine
  Normal   Created                2m               kubelet, node5     Created container
  Normal   Started                2m               kubelet, node5     Started container
  Normal   Pulled                 2m               kubelet, node5     Container image "prom/mysqld-exporter@sha256:a1eda24a95f09a817f2cf39a7fa3d506df88e76ebdc08c0293744ebaa546e3ab" already present on machine
  Normal   Created                2m               kubelet, node5     Created container
  Normal   Started                2m               kubelet, node5     Started container
  Warning  Unhealthy              1m               kubelet, node5     Readiness probe failed: ERROR 2013 (HY000): Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 104
/bin/sh: 1: [: =: argument expected

**Comment by solsson** [comment]
Could be that the readiness command fails to handle some condition. Let's look at #16 first, to see what's happening with the probe there.
