### ISSUE TITLE
 Failed to open backend connection: -131 (State not recoverable)

### ISSUE THREAD

**Issue by 13567436138** [Yolean/kubernetes-mysql-cluster#18]
2018-04-08  9:21:53 140614723073920 [Note] WSREP: gcomm: connecting to group 'my_wsrep_cluster', peer 'alpaca-mariadb-0.alpaca-mariadb:,alpaca-mariadb-1.alpaca-mariadb:'
2018-04-08  9:21:53 140614723073920 [ERROR] WSREP: failed to open gcomm backend connection: 131: No address to connect (FATAL)
         at gcomm/src/gmcast.cpp:connect_precheck():282
2018-04-08  9:21:53 140614723073920 [ERROR] WSREP: gcs/src/gcs_core.cpp:gcs_core_open():208: Failed to open backend connection: -131 (State not recoverable)
2018-04-08  9:21:53 140614723073920 [ERROR] WSREP: gcs/src/gcs.cpp:gcs_open():1458: Failed to open channel 'my_wsrep_cluster' at 'gcomm://alpaca-mariadb-0.alpaca-mariadb,alpaca-mariadb-1.alpaca-mariadb': -131 (State not recoverable)
2018-04-08  9:21:53 140614723073920 [ERROR] WSREP: gcs connect failed: State not recoverable
2018-04-08  9:21:53 140614723073920 [ERROR] WSREP: wsrep::connect(gcomm://alpaca-mariadb-0.alpaca-mariadb,alpaca-mariadb-1.alpaca-mariadb) failed: 7

**Comment by 13567436138** [comment]
`[root@node1 alpaca]# kubectl logs alpaca-mariadb-0  -n mysql  -c init-config
+ HOST_ID=0
++ dnsdomainname -d
+ STATEFULSET_SERVICE=alpaca-mariadb.mysql.svc.cluster.local
++ dnsdomainname -A
+ POD_FQDN=
+ echo 'This is pod 0 () for statefulset alpaca-mariadb.mysql.svc.cluster.local'
This is pod 0 () for statefulset alpaca-mariadb.mysql.svc.cluster.local
+ '[' -z /data/db ']'
+ SUGGEST_EXEC_COMMAND='kubectl --namespace=mysql exec -c init-config alpaca-mariadb-0 --'
WARNING: unexpected service name alpaca-mariadb.mysql.svc.cluster.local, Peer detection below may fail falsely.
+ [[ alpaca-mariadb.mysql.svc.cluster.local = mariadb.* ]]
+ echo 'WARNING: unexpected service name alpaca-mariadb.mysql.svc.cluster.local, Peer detection below may fail falsely.'
+ '[' 0 -eq 0 ']'
+ echo 'This is the 1st statefulset pod. Checking if the statefulset is down ...'
+ getent hosts mariadb
This is the 1st statefulset pod. Checking if the statefulset is down ...
10.233.97.130   mariadb.mysql.svc.cluster.local
10.233.97.140   mariadb.mysql.svc.cluster.local
10.233.97.173   mariadb.mysql.svc.cluster.local
+ '[' 0 -eq 2 ']'
+ tee /tmp/mariadb-start-config
++ mktemp -u
+ grep -e '^version' -e '^datadir' -e '^wsrep' -e '^binlog' -e '^character-set' -e '^collation'
+ mysqld --verbose --help --log-bin-index=/tmp/tmp.YdgD8hH7Td
2018-04-08  9:20:04 140140612294528 [Note] Plugin 'FEEDBACK' is disabled.`

**Comment by solsson** [comment]
Please use preformatted markdown syntax. Did you notice "WARNING: unexpected service name alpaca-mariadb.mysql.svc.cluster.local, Peer detection below may fail falsely."?

**Comment by 13567436138** [comment]
how to use preformatted markdown syntax

**Comment by 13567436138** [comment]
why my service name is wrong

**Comment by 13567436138** [comment]
```
[root@node1 alpaca]# kubectl logs alpaca-mariadb-0  -n mysql  -c init-config
+ HOST_ID=0
++ dnsdomainname -d
+ STATEFULSET_SERVICE=alpaca-mariadb.mysql.svc.cluster.local
++ dnsdomainname -A
+ POD_FQDN=
+ echo 'This is pod 0 () for statefulset alpaca-mariadb.mysql.svc.cluster.local'
This is pod 0 () for statefulset alpaca-mariadb.mysql.svc.cluster.local
+ '[' -z /data/db ']'
+ SUGGEST_EXEC_COMMAND='kubectl --namespace=mysql exec -c init-config alpaca-mariadb-0 --'
WARNING: unexpected service name alpaca-mariadb.mysql.svc.cluster.local, Peer detection below may fail falsely.
+ [[ alpaca-mariadb.mysql.svc.cluster.local = mariadb.* ]]
+ echo 'WARNING: unexpected service name alpaca-mariadb.mysql.svc.cluster.local, Peer detection below may fail falsely.'
+ '[' 0 -eq 0 ']'
+ echo 'This is the 1st statefulset pod. Checking if the statefulset is down ...'
+ getent hosts mariadb
This is the 1st statefulset pod. Checking if the statefulset is down ...
10.233.97.130   mariadb.mysql.svc.cluster.local
10.233.97.140   mariadb.mysql.svc.cluster.local
10.233.97.173   mariadb.mysql.svc.cluster.local
+ '[' 0 -eq 2 ']'
+ tee /tmp/mariadb-start-config
++ mktemp -u
+ grep -e '^version' -e '^datadir' -e '^wsrep' -e '^binlog' -e '^character-set' -e '^collation'
+ mysqld --verbose --help --log-bin-index=/tmp/tmp.YdgD8hH7Td
2018-04-08  9:20:04 140140612294528 [Note] Plugin 'FEEDBACK' is disabled.
```

**Comment by 13567436138** [comment]
[[ $STATEFULSET_SERVICE = mariadb.* ]] || echo "WARNING: unexpected service name $STATEFULSET_SERVICE, Peer detection below may fail falsely."

i have several clusters ,I want to use my customed service name.

**Comment by 13567436138** [comment]
how to change init.sh script?

**Comment by 13567436138** [comment]
I changed getent hosts mariadb  
to : getent hosts alpaca-mariadb
itshows :
```
----- ACTION REQUIRED -----
No peers found, but data exists. To start in wsrep_new_cluster mode, run:
  kubectl --namespace=mysql exec -c init-config alpaca-mariadb-0 -- touch /tmp/confirm-new-cluster
Or to start in recovery mode, to see replication state, run:
  kubectl --namespace=mysql exec -c init-config alpaca-mariadb-0 -- touch /tmp/confirm-recover
Or to try a regular start (for example after recovery + manual intervention), run:
  kubectl --namespace=mysql exec -c init-config alpaca-mariadb-0 -- touch /tmp/confirm-resume
Waiting for response ...
```
I have tried there three options,still fail to start up.

**Comment by 13567436138** [comment]
@solsson  could you give me some help?

**Comment by solsson** [comment]
I think it gets further now. I suppose your database doesn't have any contents, so maybe you could delete/wipe the volumes and start over?
